# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TVShows' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TVShows
  pod 'MBProgressHUD', '~> 1.1.0'
  pod 'Alamofire'
  pod 'SVProgressHUD'
  pod 'CodableAlamofire'
  pod 'Kingfisher', '~> 5.0'

end
